name: ds-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - xgboost
  - pyarrow
  - jupyter
  - ipykernel
  - pytest
  - black
  - pip
  - pip:
      - yfinance>=0.2.30
      - tqdm>=4.66.0
      - jupyterlab>=4.0.0
      # - shap>=0.45.0
